dataset:
  batch_size: 32
  filepath: src/data/processed/patient_features_without_ctdna.csv
  id_column: patient_id
  num_classes: 4
  num_features: 6
  target_column: label
model:
  save_path: best_model.pth
  type: xgboost
models:
  cnn:
    dropout_rate: 0.45
    early_stopping_patience: 20
    enabled: true
    epochs: 50
    kernel_size: 3
    learning_rate: 0.001
    loss_type: label_smoothing
    lr_scheduler_factor: 0.5
    lr_scheduler_patience: 7
    out_channels:
    - 32
    - 64
    smoothing: 0.1
    weight_decay: 0.02
  ffn:
    activation: leaky_relu
    dropout_rate: 0.15
    early_stopping_patience: 20
    enabled: true
    epochs: 50
    hidden_dim: 32
    hidden_dims:
    - 24
    - 8
    learning_rate: 0.001
    loss_type: label_smoothing
    lr_scheduler_factor: 0.5
    lr_scheduler_patience: 7
    resffn: null
    smoothing: 0.1
    weight_decay: 0.01
  resffn:
    activation: leaky_relu
    dropout_rate: 0.15
    early_stopping_patience: 20
    epochs: 50
    hidden_dim: 32
    learning_rate: 0.001
    loss_type: label_smoothing
    lr_scheduler_factor: 0.5
    lr_scheduler_patience: 7
    smoothing: 0.1
    weight_decay: 0.01
  xgboost:
    colsample_bytree: 0.65
    early_stopping_rounds: 30
    enabled: true
    learning_rate: 0.03
    max_delta_step: 1
    max_depth: 5
    mi_k: 10
    mi_select: true
    n_estimators: 600
    n_trials: 30
    objective: multi:softprob
    subsample: 0.65
    tune: true
project:
  artifacts_dir: ./outputs
  name: cfDNA_cancer_classifier
  seed:
  - 1
  - 10
  - 32
  - 42
  version: 1.0.0
